host: 127.0.0.1
port: 8001
user_name: Miko


# https://rentry.org/llm-settings
# https://huggingface.co/docs/transformers/main_classes/configuration
llm_settings:
  language_model: TheBloke/Nous-Hermes-2-SOLAR-10.7B-GPTQ
  temperature : 0.8
  top_k: 50
  top_p: 1.0
  repetition_penalty: 1.2
  